name: Build and Scan Backend  Image

on:
  workflow_dispatch:
   

jobs:
  build-and-scan_backend_image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'
          cache: true     

      - name: Install dependencies and test
        working-directory: ./backend
        run: |
          go mod download

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./backend             
          file: ./backend/Dockerfile  
          load: true             
          tags: :harsh9308/skillpulse-backend${{ github.sha }}
          

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'harsh9308/skillpulse-backend:${{ github.sha }}'
          format: 'table'
          exit-code: '1' 
          severity: 'CRITICAL,HIGH'
