name: Depedency check
on: 
    workflow_dispatch:
jobs: 
    Depedency_check:
        runs-on: ubuntu-latest
        steps: 
            - name: code-checkout
              uses: actions/checkout@v4
            
            - name: Run govulncheck
              uses: golang/govulncheck-action@v1
              with:
               go-version-input: '1.22'
               go-package: './backend/...' 