name: Depedency check
on: 
    workflow_dispatch:
jobs: 
    Depedency_check:
        runs-on: ubuntu-latest
        steps: 
            - name: code-checkout
              uses: actions/checkout@v4
            
            - name: Submit Go Dependencies
              uses: actions/go-dependency-submission@v1
              with:
    
               working-directory: 'backend'
 