name: Frontend image linter
on: 
    workflow_dispatch: 
jobs: 
    Frontend_image_linter: 
        runs-on: ubuntu-latest
        steps: 
            - name: code checkout
              uses: actions/checkout@v4

            - name: Run Trivy on Public Docker Hub Image
              uses: aquasecurity/trivy-action@master
              with:
               image-ref: 'docker.io/harsh9308/harsh9308/skillpulse-frontend:latest'
               format: 'table'
               severity: 'CRITICAL'